In [12]:
import tensorflow as tf
from tensorflow import keras

from sklearn.preprocessing import OneHotEncoder

from keras.layers import Input, Dense, Activation
from keras.models import Sequential
from keras.models import Model

import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

print(tf.__version__)

#the first thing we need to do is get the data and the labels for the data. 
DataFrameMain = pd.read_csv("C:/Users/tsmar/election_dataframe.csv")
DataFrame = DataFrameMain.select_dtypes(include=["int", "float"])
headers = list(DataFrame.columns.values)
jj = int(0.8*len(DataFrame))
kk = int(0.2*len(DataFrame))

#these are the columns I will train on for now.
DataFrame["meanGOP"] = DataFrame[["Republicans 2016", "Republicans 2012", "Republicans 2008"]].mean(axis=1) / 100
DataFrame["meanDEM"] = DataFrame[["Democrats 2016", "Democrats 2012", "Democrats 2008"]].mean(axis=1) / 100
DataFrame["Percent of adults with a bachelor's degree or higher, 2012-2016"] = DataFrame["Percent of adults with a bachelor's degree or higher, 2012-2016"] / 100
DataFrame["Percent of adults completing some college or associate's degree, 2012-2016"] = DataFrame["Percent of adults completing some college or associate's degree, 2012-2016"] / 100
DataFrame["Percent of adults with a high school diploma only, 2012-2016"] = DataFrame["Percent of adults with a high school diploma only, 2012-2016"] / 100
DataFrame["Percent of adults with less than a high school diploma, 2012-2016"] = DataFrame["Percent of adults with less than a high school diploma, 2012-2016"]/100
#make test and train data split 80/20
trainData = DataFrame[["meanGOP","meanDEM","Percent of adults with a bachelor's degree or higher, 2012-2016","Percent of adults completing some college or associate's degree, 2012-2016","Percent of adults with a high school diploma only, 2012-2016","Percent of adults with less than a high school diploma, 2012-2016"]][0:jj]
testData = DataFrame[["meanGOP","meanDEM","Percent of adults with a bachelor's degree or higher, 2012-2016","Percent of adults completing some college or associate's degree, 2012-2016","Percent of adults with a high school diploma only, 2012-2016","Percent of adults with less than a high school diploma, 2012-2016"]][-1*kk:]
trainLabels = []
testLabels = []
#build the train Labels
for index in range(0, len(trainData["meanGOP"])):
    rawData = trainData.values
    j = rawData[index][0]
    k = rawData[index][1]
    if j > k:
        trainLabels.append(0) #gop
    else:
        trainLabels.append(1) #dem
    
#build the test labels
for index in range(0, len(testData["meanGOP"])):
    rawData = testData.values
    j = rawData[index][0]
    k = rawData[index][1]
    if j > k:
        testLabels.append(0) #gop
    else:
        testLabels.append(1) #dem
        
data_train = np.array(trainData[["Percent of adults with a bachelor's degree or higher, 2012-2016","Percent of adults completing some college or associate's degree, 2012-2016","Percent of adults with a high school diploma only, 2012-2016","Percent of adults with less than a high school diploma, 2012-2016"]].values, dtype='float64')
data_test = np.array(testData[["Percent of adults with a bachelor's degree or higher, 2012-2016","Percent of adults completing some college or associate's degree, 2012-2016","Percent of adults with a high school diploma only, 2012-2016","Percent of adults with less than a high school diploma, 2012-2016"]].values, dtype='float64') 

model = Sequential()
model.add(Dense(16, input_dim=4))
model.add(Dense(16, activation=tf.nn.relu))
model.add(Dense(16, activation=tf.nn.relu))
model.add(Dense(1, activation=tf.nn.softmax))

model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(data_train, trainLabels, epochs=3, verbose=2)

for j in range(len(data_train)):
    print(data_train[j], " should get mapped to: ", trainLabels[j])

1.11.0


C:\Users\tsmar\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\tsmar\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\tsmar\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexi

Epoch 1/3
 - 0s - loss: nan - acc: 0.1023
Epoch 2/3
 - 0s - loss: nan - acc: 0.0000e+00
Epoch 3/3
 - 0s - loss: nan - acc: 0.0000e+00
[0.24593 0.2866  0.34331 0.12417]  should get mapped to:  0
[0.29547 0.31788 0.28692 0.09972]  should get mapped to:  0
[0.12868 0.25969 0.34927 0.26236]  should get mapped to:  0
[0.12    0.26883 0.41816 0.19302]  should get mapped to:  0
[0.1305  0.34039 0.32942 0.19969]  should get mapped to:  0
[0.10255 0.2216  0.34147 0.33438]  should get mapped to:  1
[0.1608  0.25127 0.39852 0.1894 ]  should get mapped to:  0
[0.17653 0.32612 0.32072 0.17663]  should get mapped to:  0
[0.12484 0.28368 0.39411 0.19737]  should get mapped to:  0
[0.13962 0.31363 0.35958 0.18717]  should get mapped to:  0
[0.14855 0.23989 0.41254 0.19902]  should get mapped to:  0
[0.1196  0.29636 0.37257 0.21147]  should get mapped to:  0
[0.12137 0.23787 0.45118 0.18958]  should get mapped to:  0
[0.11063 0.28975 0.34575 0.25386]  should get mapped to:  0
[0.11528 0.24686 0.3797  0

[0.28226 0.37364 0.24736 0.09674]  should get mapped to:  1
[0.13957 0.30592 0.22478 0.32973]  should get mapped to:  1
[0.24492 0.32759 0.31217 0.11532]  should get mapped to:  0
[0.15665 0.30717 0.27218 0.264  ]  should get mapped to:  0
[0.12789 0.33653 0.2641  0.27149]  should get mapped to:  0
[0.16157 0.39732 0.27824 0.16287]  should get mapped to:  1
[0.12538 0.37961 0.30897 0.18604]  should get mapped to:  0
[0.30764 0.26275 0.20679 0.22282]  should get mapped to:  1
[0.1313  0.32675 0.25899 0.28296]  should get mapped to:  0
[0.57081 0.2476  0.11265 0.06893]  should get mapped to:  1
[0.22637 0.38479 0.28353 0.10532]  should get mapped to:  0
[0.24079 0.36257 0.26205 0.13459]  should get mapped to:  1
[0.13662 0.29707 0.2524  0.31391]  should get mapped to:  1
[0.1827  0.41059 0.27084 0.13587]  should get mapped to:  0
[0.30645 0.35361 0.17993 0.16001]  should get mapped to:  1
[0.23649 0.26885 0.20365 0.29101]  should get mapped to:  1
[0.33046 0.32068 0.18791 0.16095]  shoul

[0.26888 0.35931 0.2735  0.09831]  should get mapped to:  0
[0.33058 0.29656 0.29847 0.0744 ]  should get mapped to:  0
[0.35846 0.34147 0.23389 0.06618]  should get mapped to:  0
[0.29817 0.30361 0.30352 0.09471]  should get mapped to:  0
[0.12038 0.27056 0.40042 0.20864]  should get mapped to:  0
[0.09828 0.27825 0.41054 0.21293]  should get mapped to:  0
[0.07601 0.27124 0.39636 0.25639]  should get mapped to:  0
[0.22416 0.33413 0.33463 0.10708]  should get mapped to:  0
[0.16641 0.3368  0.37364 0.12316]  should get mapped to:  0
[0.26309 0.32144 0.26463 0.15084]  should get mapped to:  0
[0.10984 0.27042 0.41795 0.20179]  should get mapped to:  0
[0.11918 0.2369  0.40767 0.23625]  should get mapped to:  0
[0.06678 0.21167 0.4005  0.32105]  should get mapped to:  0
[0.13197 0.25916 0.41001 0.19885]  should get mapped to:  0
[0.11    0.26223 0.41531 0.21246]  should get mapped to:  0
[0.18422 0.26206 0.37026 0.18346]  should get mapped to:  1
[0.10986 0.21517 0.42946 0.24551]  shoul

[0.21753 0.3528  0.35745 0.07222]  should get mapped to:  0
[0.26982 0.31141 0.327   0.09178]  should get mapped to:  1
[0.22443 0.3759  0.34402 0.05566]  should get mapped to:  1
[0.27853 0.32954 0.345   0.04693]  should get mapped to:  0
[0.17999 0.33732 0.40585 0.07684]  should get mapped to:  1
[0.18698 0.28997 0.30539 0.21766]  should get mapped to:  0
[0.1567  0.35882 0.40337 0.08111]  should get mapped to:  0
[0.18375 0.37502 0.36368 0.07756]  should get mapped to:  0
[0.21427 0.32059 0.39451 0.07064]  should get mapped to:  0
[0.19831 0.27677 0.42798 0.09694]  should get mapped to:  0
[0.22047 0.35123 0.36187 0.06643]  should get mapped to:  0
[0.21859 0.40008 0.31418 0.06714]  should get mapped to:  1
[0.19163 0.36662 0.34772 0.09403]  should get mapped to:  0
[0.14481 0.31666 0.44136 0.09718]  should get mapped to:  1
[0.15395 0.31031 0.44267 0.09308]  should get mapped to:  0
[0.20865 0.37796 0.34567 0.06772]  should get mapped to:  0
[0.15309 0.30959 0.44696 0.09036]  shoul

[0.12995 0.30464 0.41015 0.15526]  should get mapped to:  0
[0.20586 0.33354 0.33336 0.12724]  should get mapped to:  0
[0.22041 0.35433 0.31154 0.11372]  should get mapped to:  1
[0.26145 0.35958 0.2844  0.09457]  should get mapped to:  1
[0.15981 0.38664 0.31427 0.13928]  should get mapped to:  0
[0.3432  0.30076 0.27838 0.07767]  should get mapped to:  0
[0.18893 0.33123 0.36764 0.11221]  should get mapped to:  0
[0.12095 0.30016 0.50192 0.07697]  should get mapped to:  0
[0.15192 0.30096 0.46978 0.07734]  should get mapped to:  0
[0.16722 0.33636 0.37344 0.12297]  should get mapped to:  0
[0.17863 0.37681 0.35176 0.0928 ]  should get mapped to:  0
[0.25011 0.34912 0.32879 0.07198]  should get mapped to:  0
[0.21295 0.31779 0.32561 0.14364]  should get mapped to:  0
[0.1396  0.32623 0.40645 0.12772]  should get mapped to:  0
[0.17177 0.39868 0.3235  0.10605]  should get mapped to:  0
[0.21937 0.30746 0.3451  0.12807]  should get mapped to:  0
[0.20874 0.37243 0.32592 0.09291]  shoul

[0.30055 0.31877 0.29535 0.08533]  should get mapped to:  0
[0.19211 0.42595 0.32691 0.05502]  should get mapped to:  0
[0.15986 0.35322 0.37655 0.11036]  should get mapped to:  0
[0.18339 0.42999 0.31766 0.06897]  should get mapped to:  0
[0.26671 0.29281 0.32977 0.11071]  should get mapped to:  0
[0.28327 0.33807 0.28897 0.08969]  should get mapped to:  0
[0.22751 0.31677 0.356   0.09973]  should get mapped to:  0
[0.17882 0.33579 0.4245  0.06089]  should get mapped to:  0
[0.21992 0.32953 0.30561 0.14495]  should get mapped to:  0
[0.24704 0.37805 0.3218  0.05311]  should get mapped to:  0
[0.25714 0.38793 0.30908 0.04586]  should get mapped to:  0
[0.1759  0.41031 0.30401 0.10979]  should get mapped to:  0
[0.16815 0.34475 0.36502 0.12207]  should get mapped to:  0
[0.14315 0.36121 0.37147 0.12417]  should get mapped to:  0
[0.21781 0.27323 0.42377 0.0852 ]  should get mapped to:  0
[0.18878 0.41126 0.31377 0.0862 ]  should get mapped to:  0
[0.20145 0.37024 0.34301 0.0853 ]  shoul

[0.12154 0.32864 0.39877 0.15105]  should get mapped to:  0
[0.29056 0.28687 0.29955 0.12301]  should get mapped to:  0
[0.1482  0.249   0.42465 0.17814]  should get mapped to:  0
[0.09299 0.22319 0.39154 0.29228]  should get mapped to:  0
[0.08946 0.26368 0.43179 0.21507]  should get mapped to:  0
[0.1785  0.23345 0.36164 0.22642]  should get mapped to:  0
[0.11817 0.18394 0.39259 0.3053 ]  should get mapped to:  0
[0.31871 0.28232 0.27971 0.11926]  should get mapped to:  0
[0.11121 0.23986 0.40363 0.2453 ]  should get mapped to:  0
[0.11876 0.2436  0.42946 0.20818]  should get mapped to:  0
[0.26605 0.26799 0.34845 0.11751]  should get mapped to:  0
[0.11414 0.19785 0.41468 0.27332]  should get mapped to:  0
[0.10135 0.21502 0.4155  0.26813]  should get mapped to:  0
[0.16334 0.26837 0.41296 0.15533]  should get mapped to:  0
[0.12962 0.28363 0.41607 0.17068]  should get mapped to:  0
[0.25967 0.33637 0.28556 0.1184 ]  should get mapped to:  0
[0.23801 0.29464 0.32821 0.13914]  shoul

[0.17375 0.35729 0.34703 0.12194]  should get mapped to:  0
[0.28498 0.32323 0.31871 0.07308]  should get mapped to:  0
[0.18259 0.32269 0.38308 0.11164]  should get mapped to:  0
[0.19711 0.32022 0.37793 0.10474]  should get mapped to:  0
[0.1137  0.33485 0.39226 0.15919]  should get mapped to:  0
[0.30712 0.35009 0.27967 0.06312]  should get mapped to:  0
[0.16678 0.35429 0.35874 0.12019]  should get mapped to:  0
[0.20578 0.38195 0.33815 0.07412]  should get mapped to:  0
[0.23402 0.31187 0.3903  0.06381]  should get mapped to:  0
[0.25227 0.39013 0.29379 0.06381]  should get mapped to:  1
[0.32882 0.35247 0.25833 0.06038]  should get mapped to:  0
[0.19903 0.37417 0.32329 0.10352]  should get mapped to:  1
[0.13392 0.31148 0.40594 0.14866]  should get mapped to:  0
[0.17545 0.36316 0.38879 0.0726 ]  should get mapped to:  1
[0.31671 0.36602 0.26183 0.05544]  should get mapped to:  0
[0.14253 0.33995 0.41313 0.10439]  should get mapped to:  0
[0.16674 0.31523 0.38864 0.1294 ]  shoul

[0.19434 0.2634  0.43508 0.10719]  should get mapped to:  0
[0.29882 0.32889 0.2841  0.08819]  should get mapped to:  0
[0.18675 0.28763 0.39651 0.12911]  should get mapped to:  0
[0.13915 0.23107 0.48254 0.14724]  should get mapped to:  0
[0.15469 0.29343 0.42189 0.13   ]  should get mapped to:  0
[0.09813 0.29398 0.42556 0.18233]  should get mapped to:  0
[0.2009  0.26428 0.43857 0.09626]  should get mapped to:  0
[0.25312 0.24916 0.38044 0.11727]  should get mapped to:  0
[0.14375 0.31061 0.393   0.15264]  should get mapped to:  0
[0.11379 0.28695 0.40749 0.19176]  should get mapped to:  0
[0.29427 0.31044 0.29356 0.10174]  should get mapped to:  1
[0.22056 0.29207 0.35769 0.12968]  should get mapped to:  0
[0.18431 0.35974 0.33051 0.12543]  should get mapped to:  0
[0.27791 0.32027 0.31585 0.08597]  should get mapped to:  0
[0.15512 0.26934 0.43736 0.13817]  should get mapped to:  0
[0.13673 0.2924  0.38867 0.18221]  should get mapped to:  0
[0.18322 0.27871 0.42724 0.11082]  shoul

[0.24749 0.35441 0.32845 0.06965]  should get mapped to:  0
[0.19851 0.4106  0.30492 0.08597]  should get mapped to:  0
[0.23726 0.38023 0.3308  0.05171]  should get mapped to:  0
[0.18904 0.37778 0.35829 0.07488]  should get mapped to:  0
[0.15899 0.35248 0.38317 0.10536]  should get mapped to:  1
[0.14762 0.41557 0.39838 0.03842]  should get mapped to:  0
[0.28602 0.31388 0.33127 0.06883]  should get mapped to:  0
[0.28925 0.36332 0.29269 0.05474]  should get mapped to:  0
[0.48019 0.29265 0.195   0.03216]  should get mapped to:  0
[0.14644 0.33905 0.45119 0.06332]  should get mapped to:  0
[0.18258 0.32724 0.38831 0.10186]  should get mapped to:  1
[0.2356  0.2548  0.44328 0.06632]  should get mapped to:  0
[0.2501  0.28612 0.35858 0.1052 ]  should get mapped to:  0
[0.23488 0.38387 0.28623 0.09502]  should get mapped to:  0
[0.33069 0.3423  0.27628 0.05073]  should get mapped to:  0
[0.31338 0.28507 0.35006 0.05148]  should get mapped to:  0
[0.24945 0.35958 0.29741 0.09356]  shoul

[0.22312 0.45432 0.24656 0.07599]  should get mapped to:  0
[0.33094 0.3545  0.2512  0.06335]  should get mapped to:  0
[0.18062 0.3348  0.37115 0.11344]  should get mapped to:  0
[0.20266 0.34584 0.32794 0.12356]  should get mapped to:  0
[0.13788 0.38032 0.36084 0.12096]  should get mapped to:  0
[0.19697 0.35522 0.35746 0.09035]  should get mapped to:  0
[0.22527 0.33333 0.3042  0.1372 ]  should get mapped to:  0
[0.13805 0.28984 0.41621 0.15591]  should get mapped to:  0
[0.20751 0.34504 0.34723 0.10022]  should get mapped to:  0
[0.18276 0.31936 0.31371 0.18417]  should get mapped to:  0
[0.2458  0.36669 0.31118 0.07633]  should get mapped to:  0
[0.18273 0.37751 0.35442 0.08534]  should get mapped to:  0
[0.20662 0.40671 0.29233 0.09435]  should get mapped to:  0
[0.25299 0.35567 0.31193 0.07941]  should get mapped to:  0
[0.23643 0.38732 0.29477 0.08147]  should get mapped to:  0
[0.1942  0.39792 0.32439 0.08348]  should get mapped to:  0
[0.17395 0.37988 0.32527 0.1209 ]  shoul

[0.19638 0.24681 0.43113 0.12568]  should get mapped to:  0
[0.13119 0.27975 0.44339 0.14567]  should get mapped to:  1
[0.29126 0.27678 0.32853 0.10343]  should get mapped to:  1
[0.17772 0.30426 0.44639 0.07163]  should get mapped to:  0
[0.16408 0.31095 0.4235  0.10147]  should get mapped to:  0
[0.12437 0.25076 0.47749 0.14737]  should get mapped to:  0
[0.29134 0.27249 0.33303 0.10314]  should get mapped to:  0
[0.11425 0.27836 0.47779 0.12959]  should get mapped to:  0
[0.16504 0.27262 0.45382 0.10851]  should get mapped to:  0
[0.17967 0.32102 0.37138 0.12793]  should get mapped to:  0
[0.27618 0.28472 0.33502 0.10408]  should get mapped to:  0
[0.16492 0.29755 0.42226 0.11527]  should get mapped to:  0
[0.13936 0.28323 0.45367 0.12374]  should get mapped to:  0
[0.12055 0.24389 0.49285 0.1427 ]  should get mapped to:  0
[0.12672 0.3004  0.45757 0.11531]  should get mapped to:  0
[0.30891 0.29339 0.28297 0.11473]  should get mapped to:  1
[0.13094 0.27289 0.48544 0.11074]  shoul

[0.21775 0.33042 0.3478  0.10402]  should get mapped to:  0
[0.26287 0.29372 0.35097 0.09244]  should get mapped to:  0
[0.21448 0.25663 0.40944 0.11946]  should get mapped to:  0
[0.26711 0.27779 0.33363 0.12148]  should get mapped to:  0
[0.2087  0.28335 0.38223 0.12572]  should get mapped to:  0
[0.22993 0.35815 0.31606 0.09587]  should get mapped to:  0
[0.53694 0.26976 0.1433  0.04999]  should get mapped to:  1
[0.34064 0.36782 0.22428 0.06726]  should get mapped to:  1
[0.24085 0.42254 0.25605 0.08055]  should get mapped to:  1
[0.19184 0.38631 0.32538 0.09648]  should get mapped to:  1
[0.18355 0.38143 0.32447 0.11055]  should get mapped to:  0
[0.16128 0.35065 0.364   0.12406]  should get mapped to:  0
[0.23575 0.38472 0.27624 0.10329]  should get mapped to:  0
[0.33313 0.36071 0.23607 0.0701 ]  should get mapped to:  0
[0.16326 0.40361 0.32416 0.10897]  should get mapped to:  0
[0.17053 0.35079 0.37771 0.10097]  should get mapped to:  0
[0.21726 0.36095 0.31816 0.10362]  shoul

[0.12995 0.25048 0.45194 0.16763]  should get mapped to:  0
[0.14976 0.22822 0.41227 0.20975]  should get mapped to:  0
[0.16103 0.25772 0.39438 0.18688]  should get mapped to:  0
[0.19419 0.28849 0.37342 0.14389]  should get mapped to:  0
[0.15788 0.29604 0.38629 0.15979]  should get mapped to:  0
[0.13187 0.23417 0.40637 0.22759]  should get mapped to:  0
[0.13747 0.15915 0.46651 0.23687]  should get mapped to:  0
[0.10244 0.2201  0.465   0.21245]  should get mapped to:  0
[0.18451 0.29476 0.37499 0.14575]  should get mapped to:  0
[0.13577 0.23432 0.39518 0.23472]  should get mapped to:  0
[0.18762 0.27027 0.37774 0.16437]  should get mapped to:  0
[0.38203 0.25997 0.23296 0.12504]  should get mapped to:  1
[0.11296 0.2469  0.46306 0.17707]  should get mapped to:  0
[0.14178 0.19763 0.44022 0.22037]  should get mapped to:  0
[0.14136 0.25431 0.44075 0.16357]  should get mapped to:  0
[0.18443 0.25552 0.39226 0.16779]  should get mapped to:  0
[0.22073 0.28826 0.3532  0.1378 ]  shoul